### ISSUE TITLE
Help using this...

### ISSUE THREAD

**Issue by TechPunk316** [jas3333/GPT-Helper#1]
Hey this is a greate project! I set this up and it runs but I can't seem to ask any questions? I'm using Firefox - am I doing something wrong? When I press enter after asking a question nothing happens...Any help appreciated

![Screenshot 2022-12-08 at 14 38 47](https://user-images.githubusercontent.com/30231796/206475152-2b1beb55-9a5c-420f-a4c4-d2b5bbfdcb73.png)

**Comment by jas3333** [comment]
Did you create a .env file in the client directory with your API key in it? Inside the file you will want to have a variable like REACT_APP_OPENAI_KEY=theapikey

**Comment by TechPunk316** [comment]
Thanks for getting back to me. Yup I called it OpenAIkey.env. Should that be ok?

**Comment by jas3333** [comment]
Can you try renaming it to just .env? Since it is using react, I believe it will be looking for just .env in the client directory.

**Comment by TechPunk316** [comment]
Thanks so much - that worked!
