### ISSUE TITLE
How do I input my API Token?

### ISSUE THREAD

**Issue by TheExodus90** [jas3333/GPT-Helper#12]
Hi using Windows / Anaconda I've managed to install it but what Command do I use to input my API Code? 

If I use REACT_APP_OPENAI_KEY=mykey I get an error 

" is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again."

**Comment by jas3333** [comment]
You need to create a file called `.env` in the client folder and place the variable in it.

**Comment by TheExodus90** [comment]
Thanks, I managed to get it working using the following command

($env:REACT_APP_OPENAI_KEY = "mykey") -and (npm start)
