### ISSUE TITLE
Model's maximun content length

### ISSUE THREAD

**Issue by JValdivia23** [jas3333/GPT-Helper#15]
The model's maximun content length is 4097 tokens, it means that you can write only 4097 words. Is there any way to increase this number?

**Comment by jas3333** [comment]
I just pushed an update for the token slider to max at 4096.

**Comment by JValdivia23** [comment]
Can that number be as huge as 10x that limit?

**Comment by jas3333** [comment]
No, the max token amount for the text model is 4096.

**Comment by JValdivia23** [comment]
I understand. Thank you.

**Comment by jas3333** [comment]
You're welcome.
