### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MaKeG0** [jas3333/GPT-Helper#20]
Hello and thank you very much for this easy tool you are providing.

I was wondering if you are thinking to bring it to mobile too in the future.
Or if you know a valid solution for mobile that does the same as your program.

Thanks

**Comment by jas3333** [comment]
That would be a fun project to build. I don't have the time right now though, but maybe in the future I could work on that. It would probably be awhile though.

**Comment by MaKeG0** [comment]
> That would be a fun project to build. I don't have the time right now though, but maybe in the future I could work on that. It would probably be awhile though. 

Sure I understand.

Thanks for replying.

**Comment by MaKeG0** [comment]
For now I'm using it with termux and seems to be fine, the only problem is the side menu that covers a good part of the chat.
Do you think there is an easy fix to make a togle button to make it appear and disappear?
Thanks.

**Comment by MaKeG0** [comment]
Can i help you with the second to do you have in the list?
the menu that get's in front of the chat is very annoing when i use it on the phone thanks to termux.
I'm quite new to web development and i know 0 react but i learn and try.

**Comment by jas3333** [comment]
I created a toggle for the settings which should help you out with the menu.

**Comment by MaKeG0** [comment]
thank you very much.
