### ISSUE TITLE
Add gpt-3.5-turbo new model

### ISSUE THREAD

**Issue by revbin** [jas3333/GPT-Helper#28]
hi

can you please add **gpt-3.5-turbo** new model
its the  most capable GPT-3.5 model and optimized for chat at 1/10th the cost of text-davinci-003. its  updated with  latest model iteration.

thanks in advance

**Comment by jas3333** [comment]
I created a new branch called gpt-3.5-turbo. It's functional for now, I need to remove some stuff from the config menu still a bit too tired right now. I need to mess with it more though. Seems I get a lot of "I apologize, I am an AI language model...." Just like chatGPT does. I'll mess with it some more tomorrow and see if I can improve it a little bit.

**Comment by jas3333** [comment]
Alright I pushed the changes now. Still need to experiment with the prompt because it will try to complete the users question.

**Comment by zeidm** [comment]
hi
to experiment the prompt , i changed **promptData** to this . will test some days to see the result .
'
const promptData = {
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'system', content: `${promptOptions}` },{ role: 'user', content: `${conversation} ${question}` }],
        stop: ['STOP'],
    };
'

**Comment by jas3333** [comment]
Changing messages to `messages: [{ role: 'user', content: `${promptOptions}\n${conversation}\n${question}\n`}],` May have fixed the issue. I pushed a new update.

**Comment by dlarue** [comment]
I tried GPT-3.5-Turbo and got strange results such that it was as if I asked it the new question along with 2 or 3 of the previous questions.
