### ISSUE TITLE
latest update negates previous client startup

### ISSUE THREAD

**Issue by dlarue** [jas3333/GPT-Helper#30]
Thanks for updating the code but I kinda liked or was used to the 'npm start' from the client directory which not only started the GPT-Helper server but also spawned a browser tab loaded to the chat server.

The current method of starting does work and I was able to write a bash script to do what the previous client did but it's not as elegant.

#!/bin/bash
HERE=`pwd`
cd ~/GPT-Helper/
google-chrome http://localhost:4001
node server.js
cd $HERE

**Comment by jas3333** [comment]
Ok just pushed an update that should do what you want.

**Comment by dlarue** [comment]
cool, running 'npm start' in the in the project root starts the server and spawns a browser tab. Thx!
