### ISSUE TITLE
Mobile fork

### ISSUE THREAD

**Issue by TrySpace** [jas3333/GPT-Helper#32]
Hey! awesome work. I've gone and forked it and made it usable on mobile: https://github.com/TrySpace/GPT-Helper

And it uses typescript and @mui components, I've also cleaned up almost all of the unused css, and other files.

PR's welcome for improvements, would love to see it merged here too, although I've changed the folder structure a bit (no need for `client` folder)

/Edit oops I see that there was a big update in the meantime, so my fork is based on a few weeks older version 😅

**Comment by jas3333** [comment]
> Hey! awesome work. I've gone and forked it and made it usable on mobile: https://github.com/TrySpace/GPT-Helper
> 
> And it uses typescript and @mui components, I've also cleaned up almost all of the unused css, and other files.
> 
> PR's welcome for improvements, would love to see it merged here too, although I've changed the folder structure a bit (no need for `client` folder)
> 
> /Edit oops I see that there was a big update in the meantime, so my fork is based on a few weeks older version sweat_smile

That looks really good. Much cleaner than what I had. My CSS skills are still lacking. 

Yeah I ended up re-writing it with a backend to make dockerizing it easier. The current docker version connects to Pinecone and a Mongo db for semantic search. Repo for that is [here](https://github.com/jas3333/gptchat_pinecone). 

Thanks for your work, I will still go through it more and see what I can learn from it. I would like to eventually learn Typescript.
