### ISSUE TITLE
Ai not responding correctly.

### ISSUE THREAD

**Issue by johnbulliner** [jas3333/GPT-Helper#4]
When i write a prompt it will continue to write as me. For example i said: "Yep" as a response. The Program Took my "Yep" and made it "You: Yep" at the top and the response was. "That's about it". The thing is that it is just continuing what i was saying instead a response from the ai. Also The ai just stop responding to me at all because it has no indication that it is its turn to talk. I think if you add a "response:" In front of what the ai says it will fix the issue of not knowing who is talking.

**Comment by johnbulliner** [comment]
It also won't stop talking about code right when i the convo starts.

**Comment by jas3333** [comment]
Yeah I need to work on prompt engineering and figure out how to use stop sequences. I'll mess around with it and see if I can fix it.

**Comment by jas3333** [comment]
Ok it should be working a bit better now. I added `'User:' ${question}\n` with some stop sequences and looks like it has stopped adding to the user question.
