### ISSUE TITLE
Nothing happens when I press enter

### ISSUE THREAD

**Issue by strouder** [jas3333/GPT-Helper#8]
I think i've set it up properly. I have the UI running and I also have a GPT.env file on my client folder (does the filename matter? the tutorial said only .env) my env file has my open AI API key attached. 

Why is this not working?

**Comment by ryuufirestorm** [comment]
I have a the .env file named just .env and I am getting the same problem.

**Comment by jas3333** [comment]
Open up the dev tools in the browser, what is the error in the console?

**Comment by jas3333** [comment]
I just added error messages to the completion section. Try downloading the latest version and trying again.

**Comment by kaijucakes** [comment]
Exceeded quota :( oh well.
