### ISSUE TITLE
No responses

### ISSUE THREAD

**Issue by Mason-Millard** [jas3333/GPT-Helper#9]
Will this still operate as normal while the ChatGPT is down/overloaded?

**Comment by jas3333** [comment]
This is just an interface to GPT3 API. IT doesn't use the Chatgpt api. So in order to use it you will need an API key and create a filed named `.env` in the client directory with your key in it.

**Comment by Mason-Millard** [comment]
I have my key in the .env file and it is located in the client directory

**Comment by jas3333** [comment]
If you open up the dev tools in the browser and check the console, what error do you get?

**Comment by jas3333** [comment]
You don't see an Axios error?

**Comment by Mason-Millard** [comment]
I don't see an Axios error. I have Node 19.2.0 (the current version)

**Comment by jas3333** [comment]
If the app isn't responding after you submit your question, you should get an Axios error in the console. So I don't know what to make of the issue. The chrome errors shouldn't prevent this from working.

**Comment by SaltyBarnacles** [comment]
I am getting the Axios error. How do I go about fixing this?

**Comment by SaltyBarnacles** [comment]
> You don't see an Axios error? Also which version of node are you using?

I am getting the Axios error. How do I go about fixing this?

**Comment by jas3333** [comment]
> > You don't see an Axios error? Also which version of node are you using?
> 
> I am getting the Axios error. How do I go about fixing this?

What is the error?
